title: Jake's Site
author: Jake Mannino
email: yomannio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  this is a description of my site

# social links
twitter_username: dontUseTwitter # DO NOT include the @ character, or else the build will fail!
github_username:  jake-mannino # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
